// config.json
{
  "auth_url": "https://auth.openstack.example/",
  "insecure": "true",
  "application_credential_id": "123456789",
  "application_credential_secret": "secret-key"
}

apiVersion: v1
kind: Secret
metadata:
  name: openstack-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      default:
        auth:
            "auth_url": "https://auth.openstack.example/",
             "insecure": "true",
             "application_credential_id": "123456789",
             "application_credential_secret": "secret-key"
          user_domain_name: Default
          project_domain_name: Default
        # region_name: RegionOne
        # interface: public
        # identity_api_version: 3

