apiVersion: v1
kind: Secret
metadata:
  name: openstack-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      default:
        auth:
          auth_url: [openstack.example.com](https://openstack.example.com:5000/v3)
          username: demo
          password: supersecret
          project_name: admin
          user_domain_name: Default
          project_domain_name: Default
        region_name: RegionOne
        interface: public
        identity_api_version: 3
---
apiVersion: openstack.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: openstack
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: openstack-credentials
      key: clouds.yaml
